# Setup
title:            Raymond Cheng
tagline:          'Home'
domain: chngr.github.io
url: https://chngr.github.io
baseurl: '/'

author:
  name:           'Raymond Cheng'
title: Raymond Cheng
email: cheng@math.uni-hannover.de
